# To validate this config:
#
#     cat codecov.yml | curl --data-binary @- https://codecov.io/validate
#
# See https://docs.codecov.io/docs for more info

# https://docs.codecov.io/docs/coverage-configuration
coverage:
  precision: 2
  round: down
  range: "90..100"

  # https://docs.codecov.io/docs/commit-status
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
