---
runtime: go112

main: ./cmd/go_httpbin

handlers:
  # Always redirect index requests to https
  - url: /
    script: auto
    secure: always
    redirect_http_response_code: 301

  # Allow requests for any other resources via either http or https
  - url: /.+
    script: auto
    secure: optional
