version: "3.9"
services:
  httpbin:
    image: openziti/go-httpbin
    build: .
    environment:
      - ENABLE_ZITI=true
      - ZITI_SERVICE_NAME=${ZITI_SERVICE_NAME:-httpbin}
      - ZITI_IDENTITY=${ZITI_IDENTITY-/mnt/ziti_id.json}
    volumes:
      - .:/mnt
