name: ci

on:
  push:
    branches: [main] # pushes TO main
  pull_request:
    branches: [main] # pull requests AGAINST main

permissions:
  contents: read

# cancel CI runs when a new commit is pushed to any branch except main
concurrency:
  group: "test-${{ github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build against the two latest releases, to match golang's release
        # policy: https://go.dev/doc/devel/release#policy
        go-version:
        - 'stable'
        - 'oldstable'

    steps:
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{matrix.go-version}}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: test
      run: make testci

    - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      if: ${{ matrix.go-version == 'stable' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 'stable'

      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest

  lint-github-actions:
    name: lint-github-actions
    runs-on: ubuntu-latest
    permissions:
      security-events: write # required zizmor to report security findings
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          inputs: .github
          persona: pedantic
