name: Lint

on:
  push:
    branches: [master] # pushes TO master
  pull_request:
    branches: [master] # pull requests AGAINST master

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0
